server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ =404;
    }

    location /admin {
        proxy_pass http://172.17.0.1:7223;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}


[400 Bad Request] during [POST] to [https://fi-bridge-dev.fbn-devops-dev-asenv.appserviceenvironment.net/api/v1/transaction/post-multiple-transactions] 
  "RequestId": null,
  "ResponseCode": "700",
  "ResponseMessage": "Client Not permitted"
}]